<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="VCtx.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FSharp.Data.Validation\FSharp.Data.Validation.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="[8.0.100,)" />
  </ItemGroup>

</Project>
